select * from customer limit 20

-- Q1.What is the total revenue generated by male vs. female customers/
select gender , SUM(purchase_amount) as revenue
from customer
group by gender

--Q2.Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3.Which are the top 5 products with the highest average review rating?
select item_purchased,ROUND(AVG(review_rating::numeric),2)as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4.Compare the average Purchase Amounts between Standard and Express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do subscribed customers spend more?Compare avarage spend and total revenue between 
--between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;